### ISSUE TITLE
ToDoApp - BackEnd - Django

### ISSUE THREAD

**Issue by ajjayymahato** [ajjayymahato/ToDoApp#4]

**Comment by 29deepanshutyagi** [comment]
kindly assign me this issue @ajjayymahato , i can prepare good backend through django .

**Comment by ajjayymahato** [comment]
Sure

**Comment by seabeePraveen** [comment]
hey @ajjayymahato i already have the code for this part instead of doing the whole project so if u assign me i will just make the PR
Thank You,
Happy Coding :)

**Comment by thouseef-hamza** [comment]
I am Interested in this issue django backend

**Comment by ajjayymahato** [comment]
@seabeePraveen @29deepanshutyagi @THOUSI731 Create a similar issue and i will assign that you.
